/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 01.05.2026 22:16:21

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10272;
#else
constexpr int kTensorArenaSize = 9248;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,4018 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0037530637346208096, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 98, 41, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 98, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 49, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 49, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 697, -479, 180, -30, };
const TfArray<1, float> quant6_scale = { 1, { 0.00052921648602932692, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[4*400] = { 
  -19, -24, -10, -19, -15, -24, -17, -17, -13, -13, -20, -23, -21, -6, -19, 38, -17, -31, -30, -21, 20, -23, -18, -3, -17, -12, -19, -21, -20, 105, 16, -4, -14, 9, -19, -21, -10, -17, -12, 15, -15, -16, -19, -20, -8, 70, 51, -9, -14, 4, -16, -21, -34, -21, -9, -12, -19, -17, -18, -23, -11, 57, -8, 36, -20, -34, -30, -18, -19, -19, -10, -25, -18, -17, -21, -24, -21, 53, -23, 43, -22, -21, -22, -19, -5, -21, -11, -16, -17, -12, -20, -23, -18, 14, -25, 57, -18, -22, -22, -14, 8, -18, -12, -7, -23, -17, -28, -25, -19, 83, 38, 40, -25, -3, -20, -18, -36, -15, -16, -4, -13, -14, -20, -22, -17, 56, 37, 13, -29, -9, -25, -22, -37, -22, -10, -15, -14, -14, -20, -20, -17, 14, -22, 55, -26, -29, -23, -14, -1, -15, -18, -13, -18, -13, -21, -24, -21, 81, 26, 30, -29, -10, -13, -13, -29, -18, -10, -3, -20, -13, -17, -17, -18, 50, 48, -3, -17, -6, -22, -21, -26, -17, -11, -13, -18, -14, -21, -25, -14, 19, -20, 25, -26, -34, -24, -25, -34, -23, -20, -7, -22, -14, -24, -24, -23, 22, 22, 10, -26, -22, -27, -11, -10, -17, -15, -10, -22, -17, -25, -26, -18, 65, -1, 25, -19, -13, -26, -23, -9, -16, -15, -13, -19, -14, -22, -19, -20, 73, 12, 35, -13, -14, -22, -16, -25, -19, -9, -8, -18, -11, -24, -20, -16, 4, 8, 21, -18, -22, -19, -21, 1, -17, -15, -19, -22, -15, -19, -20, -12, 0, -28, 25, -16, -34, -26, -26, 28, -23, -15, -3, -22, -17, -23, -24, -19, 55, 30, -5, -20, -12, -22, -26, -20, -22, -16, 4, -18, -16, -25, -20, -13, 92, 28, 2, -23, -17, -25, -15, -15, -19, -11, -11, -13, -19, -21, -24, -21, 34, -17, 11, -18, -36, -28, -25, -30, -17, -10, -8, -19, -18, -20, -26, -17, 68, 14, 5, -24, -13, -16, -16, -15, -24, -19, -22, -24, -20, -26, -21, -14, 16, -4, 72, -19, -24, -29, -18, -3, -21, -15, -7, -17, -21, -20, -28, -21, 105, 10, 85, -22, -24, -21, -13, -2, -22, -17, -5, -18, -20, -25, -25, -17, 110, -6, 31, -22, -16, -15, -16, -5, -21, 9, -10, -14, -11, -15, -19, -13, 127, 50, 6, 
  2, 4, -9, -11, 13, -13, -13, -7, -12, -10, -8, -9, -7, -8, -7, 11, 16, 28, 5, -2, 18, -8, -6, 3, -3, -8, -11, -2, -4, 48, 32, 9, 20, 14, 4, -11, 17, -12, -11, 12, -11, -6, -12, -2, -8, 40, 7, 8, 25, 20, 6, -5, 25, -12, -8, 3, -5, -7, -7, -4, -9, 30, 23, 12, 4, 17, 14, -2, 14, -10, -6, 3, -12, -10, -8, -11, 0, 28, 13, 13, 12, 11, -3, -5, 18, -12, -12, 19, -3, -6, -11, -11, -10, 36, 27, 6, 5, 19, 5, -11, 20, -7, -8, 15, -6, 0, -9, -9, -7, 27, 26, 2, 19, 11, 0, -3, 30, -10, -7, 9, -6, -4, -3, -3, 2, 42, 15, 11, 27, 31, 5, -4, 43, -11, -2, 9, -9, -7, -8, -8, -4, 34, 30, 18, 17, 20, 12, -2, 14, -2, -7, 11, -8, -9, -8, -3, 2, 4, 18, 25, 36, 4, -6, -13, 32, -9, -5, 10, -12, -7, -7, -9, -5, 27, 31, 10, 21, 11, -3, -12, 37, 0, -7, 19, -5, 0, -12, -2, 3, 50, 20, -5, 38, 31, 11, -15, 34, -5, -1, 35, -3, -8, -13, -3, 4, 45, 34, -11, 30, 19, 12, -10, 16, -6, -5, 22, -3, 0, -10, -8, -5, 38, 20, -6, 14, 15, 11, -7, 14, -9, -3, 15, -4, -2, -7, -9, -7, 6, 11, 6, 21, 24, 2, -8, 25, 0, -6, 22, -12, -10, -11, -9, -4, 33, 40, -1, 18, 20, 4, -12, 40, -10, -3, 11, -6, -2, -10, 1, 2, 48, 27, -7, 30, 39, 13, -4, 17, 4, 1, 11, -2, 0, -2, -4, 10, 20, 47, -11, 21, 25, 12, -6, 23, -8, -1, 25, -6, 1, -7, 2, -8, 24, 11, 7, 21, 29, 18, -4, 16, -3, 2, 13, -9, 2, -7, -7, 8, 7, 11, 9, 21, 17, -2, -7, 30, 0, -8, 20, -7, -1, -7, -5, -9, 28, 29, 1, 20, 13, 2, -14, 33, -7, -6, 23, -4, -1, -2, -2, 1, 16, 24, -10, 26, 18, 13, -8, 26, -4, -5, 35, -5, 1, -9, -7, 5, 25, 32, -17, 32, 3, 7, -10, 12, -9, 4, 27, -2, 0, -7, 2, -1, -1, 0, -15, 6, 1, -6, -12, 16, -1, 14, 3, -4, 4, 2, -4, 16, -29, 25, -12, 
  5, 7, 0, 3, 1, -5, 19, 3, 5, -6, 7, 7, 9, 4, 4, 15, 6, -9, -1, 28, -3, 1, -3, -5, -5, -11, -7, 2, -8, -12, -4, 20, -3, 6, 17, 30, -1, -8, 0, -5, 0, -7, 5, 10, -4, -32, -12, 22, 5, -17, 5, 14, 8, 2, -8, -8, 7, 2, 8, -7, -6, -21, -5, 9, 12, 3, 10, 12, 6, -1, 3, 3, -4, 0, 11, 2, 1, -18, 22, 7, 6, 5, 1, 21, -2, -3, 14, -9, -5, -1, 9, 6, -2, -29, -2, 4, -1, -10, 7, 28, -3, -9, -11, 2, 1, -1, 2, 3, -6, -6, 3, 15, 4, 3, 6, 25, -7, -9, 4, -3, 4, -11, 6, -1, -3, -37, -9, 15, 3, -16, 11, 11, 3, 6, 3, -11, -4, -7, -3, 0, -9, -20, -1, 9, 9, 0, 8, 34, 6, 5, 0, 4, 5, -6, 10, 0, -6, -24, 11, 1, -1, 9, 12, 20, 0, 6, 10, 0, -2, -4, 12, -6, 5, -33, 1, 8, -4, -1, 5, 20, -8, -10, -1, -4, -4, -5, 13, 0, 1, -13, -3, 19, -5, 14, 9, 40, -5, 1, -1, -8, 6, -11, 5, 8, -8, -35, -15, 32, 4, -21, -5, 7, 4, -5, -8, -12, -4, -2, -5, -5, -4, -21, -2, 13, -1, -2, 21, 29, 5, 1, -8, -5, 1, -10, 9, -2, 2, -23, 7, 22, 1, 8, 12, 10, -7, -4, 6, -8, -5, -2, 0, 1, 6, -37, -15, 17, -1, -10, 0, 17, -1, 0, -6, -5, 2, -13, 3, 6, -8, -2, -3, 22, -4, 8, 9, 32, -2, -1, 5, -9, -2, -9, 4, -4, -5, -37, -12, 34, -3, -16, -7, 4, 2, -8, -7, -7, -6, 1, -5, -6, -4, -16, -3, 12, 0, 3, 7, 7, 4, -7, -3, 0, -1, -7, 2, 3, 6, -3, 5, 17, -2, 3, 18, 13, 2, -10, 0, -1, -1, 0, -1, -3, -1, -19, -6, 14, -12, -7, 15, 29, -4, -6, -7, -4, -6, -9, 0, -3, -4, -4, 5, 35, -5, 13, 9, 36, -6, -7, 7, -6, 5, -9, -5, 12, -7, -35, -15, 34, 1, 1, -8, 15, 2, -8, -6, -10, 6, -9, -5, 7, 3, 9, 11, 14, -3, 4, 6, 22, 16, -4, -11, 2, -5, -19, 8, -1, -11, 33, 23, 8, 
  -5, -3, -3, -1, 2, 2, 5, 0, -1, 0, 4, 10, -4, -7, 8, -12, -2, -3, -9, -5, 8, 1, 14, -3, 4, 3, 13, -4, 1, -8, -12, -27, 1, -13, -9, -13, 8, 3, 2, -2, 1, 11, -4, -3, 9, 11, -1, -23, -4, 8, -2, -1, -1, 9, 9, 2, 5, 10, -2, -1, 0, 5, -11, -20, -11, -3, -3, -7, 3, 14, 0, -3, 1, 13, 10, 12, -3, 0, -22, -20, -9, -5, -3, 3, 4, 13, -10, 3, 8, 8, -1, -2, -4, 8, -9, -18, -2, 0, -7, -14, 3, 3, 2, -7, 5, 14, 10, -1, 15, -13, -6, -19, -3, -16, -13, -14, 7, -1, 2, -1, -1, 5, 4, 4, 13, 7, -3, -26, -5, 5, -1, -3, 0, 6, 4, -3, 9, 16, 9, 6, 13, 0, -8, -16, -3, -10, -11, -8, 4, 14, 13, -2, 2, 1, 6, -2, -1, 7, -20, -21, -13, -14, -1, -6, 2, 3, -5, -1, 5, 7, -1, 4, 10, 9, -3, -15, 7, 1, -7, -12, 7, 14, 7, -5, 7, 3, -1, 7, 14, -5, -13, -23, -6, -17, -9, -16, 6, 10, 5, -1, 5, 8, 4, -5, 1, 10, -5, -31, -9, 2, -6, -5, 1, 11, 1, 4, 4, 13, -1, -2, 1, 2, -11, -15, -12, -1, -12, -4, 4, 0, 5, 2, 1, 16, 13, 1, 1, 13, -18, -15, -10, -10, -2, 3, 6, 10, -7, -1, 1, 8, 6, 15, 9, 18, 1, -13, 0, 12, -9, -10, 1, 4, 15, 2, 0, 21, 0, -1, 7, -18, -12, -26, -7, -15, -6, -13, 4, 10, -4, 6, -3, 12, 7, -4, 13, 17, -2, -22, -8, 5, 3, -4, 1, -1, 5, -3, 2, 2, 13, 4, 1, -3, -7, -14, -5, -11, -9, -10, 0, 8, 4, 3, 2, 1, 5, 8, 4, -1, -9, -14, -9, -9, -1, -11, -1, 9, -3, -2, -1, 11, 6, -2, 1, 2, -10, -16, 1, 2, -6, -14, 0, 1, 17, 0, -1, 11, 1, 6, 6, -7, -13, -22, -9, -19, -8, -12, 1, 7, 2, 5, 10, 9, 8, -4, 2, 16, -6, -23, -6, 5, 1, 1, 1, 1, 0, -2, 4, 10, -1, 6, 5, -18, 1, -10, 6, -3, -6, 1, 19, 3, 0, 3, -1, 16, -6, 4, 18, -26, -14, -12, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 4,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.016576662659645081, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -214, 1683, 1242, 1549, 153, -590, 73, -228, -541, -595, 1956, -656, 99, 667, 187, 1040, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00010545215627644211, 5.9540288930293173e-05, 5.8131343394052237e-05, 3.7539448385359719e-05, 0.00014022209506947547, 6.8624118284787983e-05, 5.6087174016283825e-05, 0.00011048180749639869, 6.4046384068205953e-05, 5.9771991800516844e-05, 4.0993552829604596e-05, 4.93248226121068e-05, 5.4924716096138582e-05, 0.0002634325937833637, 0.00017142156139016151, 0.0002550025237724185, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -10,61,14,17,-23,-11,30,13, -15,67,-21,-13,-40,-6,78,-23, -29,127,-17,-5,-39,-24,60,1, 
  /* [1][0][][] */ 29,114,-34,43,-18,-46,32,15, 3,25,-49,-3,18,27,88,38, 127,66,-27,-60,-44,-64,45,-20, 
  /* [2][0][][] */ 1,62,-46,5,-1,-50,42,21, 60,20,-13,27,20,-76,34,44, -38,73,-21,-34,-4,-51,127,-6, 
  /* [3][0][][] */ 70,-75,-16,-19,104,-124,-37,38, 41,-86,-45,77,27,-126,-12,10, -38,-19,-56,-27,72,-127,81,26, 
  /* [4][0][][] */ 7,5,-18,-9,-22,-16,16,8, -10,37,-18,-16,-12,4,16,-7, -4,127,-3,-5,-10,20,15,2, 
  /* [5][0][][] */ -82,5,-18,45,-24,15,-84,60, -70,-25,-39,-4,11,127,-101,-12, -57,4,-19,29,-13,63,-93,32, 
  /* [6][0][][] */ 18,29,3,87,-1,34,127,48, -8,-62,4,-23,-68,18,-14,59, -1,-77,-37,33,-60,58,-102,-23, 
  /* [7][0][][] */ 7,127,-13,-48,-42,26,32,2, 25,110,8,5,6,8,33,12, -13,51,-13,-20,13,-4,33,7, 
  /* [8][0][][] */ -53,-92,11,56,61,-2,48,46, -127,-114,-45,52,71,1,-53,71, -110,-102,11,52,13,53,-50,8, 
  /* [9][0][][] */ -26,-40,-17,50,-55,127,-35,31, -36,-14,-38,-25,-39,121,-75,9, -45,-7,-49,52,-39,101,-81,44, 
  /* [10][0][][] */ -55,-118,-68,55,66,-48,45,8, -42,-115,-57,16,21,-80,-52,46, -19,-80,-69,74,25,-4,-15,127, 
  /* [11][0][][] */ -95,51,-62,55,83,-72,21,-23, -98,-85,-9,-15,99,-127,44,25, -73,-42,-60,28,-21,-110,-35,-7, 
  /* [12][0][][] */ -74,52,-52,66,-25,45,16,6, 42,64,-63,-16,-61,127,-59,-14, 12,73,-6,23,20,4,0,35, 
  /* [13][0][][] */ 127,39,-8,-9,-30,29,-11,-12, 120,54,-9,-3,-7,4,12,-16, 70,62,1,6,45,-8,21,7, 
  /* [14][0][][] */ 30,59,-5,-27,-15,-4,16,-17, 11,127,-1,-7,-6,-6,36,-12, 63,13,-11,16,-2,-18,17,-12, 
  /* [15][0][][] */ 127,5,-9,-8,24,-11,-16,10, 73,8,-4,-7,15,-14,-7,3, 80,9,-2,-5,12,-12,8,10, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0084903333336114883, 0.0047938032075762749, 0.0046803639270365238, 0.0030224362853914499, 0.011289786547422409, 0.0055251750163733959, 0.0045157806016504765, 0.0088952882215380669, 0.0051566050387918949, 0.0048124585300683975, 0.0033005387522280216, 0.0039713191799819469, 0.0044221868738532066, 0.021209908649325371, 0.013801767490804195, 0.020531171932816505, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 20510, 3326, 37, -6889, 3948, -2282, 1574, 2910, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.1350675777066499e-05, 1.2501127457653638e-05, 5.4165966503205709e-06, 1.3798444342683069e-05, 1.5838639228604734e-05, 1.6928495824686252e-05, 1.1571895811357535e-05, 8.9921059043263085e-06, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*41] = { 
  /* [0][0][][] */ -74,-31,-39,-10,-88,-80,-20,-5,-36,-32,24,-36,49,-29,-27,50,-5,0,-6,-31,33,12,35,65,26,-13,8,-77,-33,-105,-100,19,27,-21,44,13,30,-9,65,56,-9, -25,-71,24,-18,-48,0,-16,12,-11,47,85,-29,63,52,97,127,41,17,58,-22,61,51,18,6,-33,40,-2,24,-71,-85,11,-56,-34,-8,28,82,50,-23,45,51,-27, -39,-97,4,-79,-106,-100,-93,34,-43,-70,17,-47,-41,-3,-26,-3,34,-25,26,-14,7,35,13,-33,-69,-4,-23,-65,-107,-110,-64,-69,-26,-26,-29,85,59,46,-26,-39,-42, 
  /* [1][0][][] */ -51,-40,-22,-5,-86,8,-53,50,-30,-27,-14,-22,47,-38,56,12,-56,-22,75,67,24,-29,29,24,12,-34,-50,-46,-58,-39,-49,-87,-49,-12,-32,-7,-64,-70,-40,-86,-26, 6,-16,13,-16,20,26,62,18,-31,-20,2,50,-24,-25,66,22,-33,-16,-1,49,84,-15,8,-25,2,10,-21,-18,26,-45,-41,-26,41,-12,-30,-40,-23,-23,-70,13,-81, 38,12,-12,44,35,21,-19,49,-26,56,107,-2,24,46,22,85,97,9,8,47,-17,56,74,127,1,95,7,-26,35,-27,5,-44,-14,49,40,13,-25,35,4,42,-52, 
  /* [2][0][][] */ 54,72,-68,-32,-74,-83,4,8,-75,-21,-1,-77,19,-103,-79,10,7,-81,44,18,58,-36,-29,-21,-16,-83,-84,-92,-35,-98,-84,-18,-93,15,54,-66,-2,-90,-47,-63,-11, 8,7,-38,1,-14,6,-61,26,-87,36,-82,-69,-20,35,7,-95,-56,27,49,4,40,-46,-29,-82,32,-64,-38,-89,-87,-70,17,-97,-11,-46,-63,-96,-3,-99,-72,9,-88, -30,2,46,-23,55,63,26,-72,-73,-12,-14,8,-18,21,-89,-70,127,-97,65,11,-44,-24,22,-102,-33,-80,-31,12,-10,-54,-27,-84,7,-76,-17,38,-75,-82,-9,9,-91, 
  /* [3][0][][] */ -10,18,46,-48,84,13,92,-10,121,14,-5,-38,-1,12,2,-1,88,25,17,7,38,40,11,6,6,37,30,-30,83,64,72,25,6,-8,1,2,-24,-11,-51,41,0, 4,15,6,40,71,121,-5,48,107,29,-9,-24,-25,50,-38,60,71,10,23,32,26,-1,24,-36,-40,26,-48,19,-1,110,127,7,-39,-55,-46,-26,-42,31,-29,41,33, 36,-31,37,28,36,23,-30,-12,120,17,-47,-4,-49,-3,-8,-8,-5,58,-41,18,-24,9,-53,-43,43,-1,31,-31,80,14,42,-22,-69,-44,-28,-73,-58,-30,9,-42,22, 
  /* [4][0][][] */ 56,-31,-34,59,-18,-4,3,43,-47,-57,-36,21,9,27,-6,23,-51,-52,-42,-48,-40,-46,-21,11,-31,-2,8,17,32,-37,-49,38,9,24,85,-4,-1,81,2,38,25, 23,25,-41,3,12,38,-12,22,-49,-51,21,-12,23,-17,1,-34,-14,-2,-30,-28,10,24,49,7,45,19,0,1,45,-57,24,-11,2,107,93,14,41,-18,26,78,-44, -27,-21,-54,5,32,4,-7,-10,-53,-20,32,42,-44,11,-28,-41,-24,-23,-10,-22,-21,-34,5,-17,-29,-3,1,38,29,-64,17,43,4,105,127,98,11,-21,12,10,-38, 
  /* [5][0][][] */ -46,-2,12,-26,-7,-2,-36,-18,54,127,-20,30,2,10,-26,18,-2,49,12,63,7,11,16,-65,-15,-48,-16,13,-30,86,-3,4,-37,-53,-19,-14,-10,-26,28,-14,-8, -96,-24,19,-42,-41,-39,-44,-53,23,26,-36,-13,20,-31,-19,11,21,87,62,52,4,35,1,-62,-3,-42,1,4,2,11,25,-59,-32,-68,-56,-14,29,-22,-32,27,-4, 19,13,42,-23,-22,-8,-1,30,106,102,-7,29,-18,5,26,2,39,-1,46,68,4,37,-30,-53,24,12,-12,-11,2,76,24,-60,-59,-63,-39,-37,17,34,-1,46,27, 
  /* [6][0][][] */ 27,45,-34,14,-48,-33,-27,-11,-63,-73,-14,33,-16,-5,29,-10,-28,70,38,14,-7,45,48,91,15,25,85,9,12,-61,-47,-42,41,-34,-37,8,-73,23,-54,-59,-80, -37,47,-13,-23,47,31,48,55,22,-40,99,-26,59,99,1,-17,-40,72,92,-3,-36,3,42,11,127,23,58,-13,-15,23,14,-33,64,-24,49,57,28,-56,-40,-21,-73, 0,-1,-64,-26,-19,-22,93,106,-56,-64,17,-18,-24,-26,87,-36,16,-15,17,-39,47,5,69,62,-16,25,10,38,-27,-42,-51,58,17,84,-12,-51,-66,4,-20,-77,-66, 
  /* [7][0][][] */ 95,-40,-7,36,110,31,-35,19,-72,-70,71,-81,36,-66,-32,9,-30,52,-47,-31,-31,22,-58,-17,63,2,17,93,124,81,-11,-2,87,127,39,-21,54,11,59,10,6, 15,-76,-79,-59,-24,23,50,-36,-47,10,-66,12,-31,-72,-47,-70,-53,-30,-79,-39,5,30,27,-1,-17,-16,69,54,-3,-56,-4,90,62,111,54,31,39,8,32,47,-1, -8,-70,-83,-5,33,18,-10,-11,-90,-65,-76,-6,-10,34,-4,20,-5,-52,-48,9,24,41,-48,78,17,67,2,50,44,52,-50,7,-23,47,-20,-26,41,37,-21,-21,48, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,41 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0030243759974837303, 0.0033309126738458872, 0.0014432466123253107, 0.0036765814293175936, 0.0042201890610158443, 0.0045105805620551109, 0.0030833198688924313, 0.0023959374520927668, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,98,41 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,98,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.012420261278748512, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,98,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,49,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,49,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,49,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.031925395131111145, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,49,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,4 } };
const TfArray<1, float> quant21_scale = { 1, { 0.72833174467086792, } };
const TfArray<1, int> quant21_zero = { 1, { -27 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4032), (TfLiteIntArray*)&g0::tensor_dimension0, 4018, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 984, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 4018, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4032), (TfLiteIntArray*)&g0::tensor_dimension13, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension15, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 392, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension17, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 784, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 784), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_870973_8_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_870973_8_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_870973_8_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_870973_8_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_870973_8_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
